events {
    worker_connections 1024;
}

http {
  upstream node_servers {
    server app-node:3000;
  }

  upstream python_server {
    server app-python:8000;
  }

  server {
    listen 80;

    location /users {
      proxy_pass http://node_servers;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /payments {
      proxy_pass http://python_server;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
